version: '3.8'

services:
  mariadb:
    image: mariadb:11.7.1-ubi9-rc  # docker pull mariadb:11.7.1-ubi9-rc
    container_name: mariadb_container
    restart: unless-stopped
    env_file:
      - .env.docker  # Cargar variables desde .env.docker
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mariadb_network

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb_container
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M  # Permitir subir archivos grandes si es necesario
    ports:
      - "8080:80"  # Acceso en http://localhost:8080
    depends_on:
      - mariadb
    networks:
      - mariadb_network

volumes:
  mariadb_data:
    driver: local

networks:
  mariadb_network:
    driver: bridge
